# Generated by Django 5.2.4 on 2025-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('precoNormal', models.IntegerField(verbose_name='Preço normal')),
                ('precoDesconto', models.IntegerField(verbose_name='Preço com desconto')),
                ('tipoDeProduto', models.CharField(verbose_name='Tipo de produto')),
                ('imagem', models.FileField(blank=True, upload_to='imagens_produto', verbose_name='Imagem')),
                ('link', models.TextField(verbose_name='Link')),
                ('loja', models.CharField(max_length=50, verbose_name='Loja')),
            ],
        ),
    ]
