# Generated by Django 5.2.4 on 2025-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='precoDesconto',
            field=models.FloatField(verbose_name='Preço com desconto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precoNormal',
            field=models.FloatField(verbose_name='Preço normal'),
        ),
    ]
