# Generated by Django 5.2.4 on 2025-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_produto_precodesconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cupom',
            field=models.CharField(blank=True, verbose_name='Cupom'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
