# Generated by Django 5.2.5 on 2025-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_produto_cupom_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug do tipo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, max_length=255, upload_to='imagens_produto', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipoDeProduto',
            field=models.CharField(max_length=100, verbose_name='Tipo de produto'),
        ),
    ]
