# Generated by Django 5.2.5 on 2025-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_produto_tipo_slug_alter_produto_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_slug',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipoDeProduto',
            field=models.CharField(verbose_name='Tipo de produto'),
        ),
    ]
