# Generated by Django 5.2.5 on 2025-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_produto_tipo_slug_alter_produto_tipodeproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipoDeProduto',
            field=models.SlugField(verbose_name='Tipo de produto'),
        ),
    ]
